CREATE TABLE cliente (
    id_cliente serial PRIMARY KEY,
    cedula varchar(15) NOT NULL,
    primer_nombre varchar(100) NOT NULL,
    segundo_nombre varchar(100) NULL,
    primer_apellido varchar(100) NOT NULL,
    segundo_apellido varchar(100) NULL,
    fecha_nacimiento date NOT NULL,
    ciudad_vivienda varchar(100) NOT NULL,
    direccion_vivienda varchar(100) NULL,
    telefono varchar(15) NULL,
    celular varchar(15) NULL,
    correo varchar(100) NULL,
    ocupacion varchar(100) NULL,
    empresa_laboral varchar(100) NULL,
    telefono_empresa varchar(100) NULL,
    disponibilidad_llamadas boolean NOT NULL,
    usa_gafas boolean NOT NULL
);

CREATE TABLE historia_clinica (
    id_historia_clinica serial PRIMARY KEY,
    fk_usuario bigint NOT NULL,
    fk_cliente bigint NOT NULL,
    patologia1 varchar(100) NULL,
    patologia2 varchar(100) NULL,
    patologia3 varchar(100) NULL,
    tratamiento1 varchar(100) NULL,
    tratamiento2 varchar(100) NULL,
    tratamiento3 varchar(100) NULL,
    cronicidad1 varchar(100) NULL,
    cronicidad2 varchar(100) NULL,
    cronicidad3 varchar(100) NULL,
    observacion1 varchar(100) NULL,
    observacion2 varchar(100) NULL,
    observacion3 varchar(100) NULL,
    anamnesis varchar(100) NOT NULL,
    rx_uso_od_esfera varchar(100) NULL,
    rx_uso_od_cilindro varchar(100) NULL,
    rx_uso_od_eje varchar(100) NULL,
    rx_uso_od_adicion varchar(100) NULL,
    rx_uso_oi_esfera varchar(100) NULL,
    rx_uso_oi_cilindro varchar(100) NULL,
    rx_uso_oi_eje varchar(100) NULL,
    rx_uso_oi_adicion varchar(100) NULL,
    vision_lejos_od varchar(100) NULL,
    vision_lejos_oi varchar(100) NULL,
    vision_cerca_od varchar(100) NULL,
    vision_cerca_oi varchar(100) NULL,
    examen_externo_od varchar(100) NOT NULL,
    examen_externo_oi varchar(100) NOT NULL,
    reflejos_pupilares_fotomotor varchar(100) NOT NULL,
    reflejos_pupilares_consensual varchar(100) NOT NULL,
    reflejos_pupilares_acomodacion varchar(100) NOT NULL,
    cover_test_vision_lejos varchar(100) NULL,
    cover_test_vision_proxima varchar(100) NULL,
    cover_test_ducciones varchar(100) NULL,
    cover_test_versiones varchar(100) NULL,
    od_oftalmoloscopio varchar(100) NOT NULL,
    oi_oftalmoloscopio varchar(100) NOT NULL,
    od_queratrometra varchar(100) NOT NULL,
    oi_queratrometra varchar(100) NOT NULL,
    od_retinoscopia varchar(100) NOT NULL,
    oi_retinoscopia varchar(100) NOT NULL,
    rx_final_od_esfera varchar(100) NULL,
    rx_final_od_cilindro varchar(100) NULL,
    rx_final_od_eje varchar(100) NULL,
    rx_final_od_adicion varchar(100) NULL,
    rx_final_oi_esfera varchar(100) NULL,
    rx_final_oi_cilindro varchar(100) NULL,
    rx_final_oi_eje varchar(100) NULL,
    rx_final_oi_adicion varchar(100) NULL,
    rx_final_od_agudes_visual varchar(100) NULL,
    rx_final_oi_agudes_visual varchar(100) NULL,
    diagnostico varchar(100) NULL,
    control varchar(100) NULL,
    observacion varchar(100) NULL
);
